# Matrix with  Numpy
<h3> numpy.random , numpy.randn , numpy.rand , numpy.randint
<h3> numpy.matlib , numpy.matlib.ones , numpy.matlib.zeros , numpy.matlib.identity , numpy.matlib.eye 

In [2]:
import numpy as np

In [26]:
arr = np.array([[0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1]])
print("Initial : \n",arr)

Initial : 
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [30]:
print("Transpose Matrix :\n",arr.T)           # Transpose matrix

Transpose Matrix :
 [[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]


In [27]:
import numpy.matlib as npm                    # to make array with zero
zrr = npm.zeros((4,3,))
print(zrr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
orr = npm.ones((4,3))                        # to make array with ones
print(orr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [29]:
eye = npm.eye(4,k=1, dtype=int)              # LU decompose
print(eye)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


In [40]:
ide = npm.identity(4, dtype=int)             # Diagonal identity
print(ide)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [6]:
rna = np.random.randint(1,5,(4,3))           # Random array with cvalue between 1 - 5
print(rna)

[[4 1 2]
 [1 4 1]
 [2 3 1]
 [4 4 4]]


In [8]:
rndm = np.random.rand(4,3)                   # 4*4 matrix 0 to 1
print(rndm)

[[0.54477683 0.00400489 0.09294167]
 [0.59691372 0.38836283 0.05125591]
 [0.08677789 0.80841491 0.16354913]
 [0.19659659 0.20682337 0.60760068]]


In [10]:
rndm = np.random.randn(4,4)                  # 4*4 matrix -1 to 1
print(rndm)

[[-0.44058596 -1.3800832   1.3145466  -0.29221771]
 [-1.64580323  2.15978967 -1.06446179 -1.18224778]
 [ 0.23647026  0.6283979  -2.08686014 -0.15306678]
 [-1.480108    0.45691388 -0.88750773 -0.9228129 ]]


# Matrix Mul, Sub, Div, Add, Dot, Square, exp, Log

In [21]:
arr = np.array([[1,0,1],
                [0,1,1],
                [1,0,1]])

brr = np.array([[1,1,2],
                [1,7,3],
                [8,1,4]])        

print("Multiplication : \n",arr*brr)
print("Divition : \n",arr/brr)
print("Addition : \n",arr+brr)
print("Subtraction : \n",arr-brr)
print("Dot : \n",np.dot(arr,brr))           # Need Square matrix

Multiplication : 
 [[1 0 2]
 [0 7 3]
 [8 0 4]]
Divition : 
 [[1.         0.         0.5       ]
 [0.         0.14285714 0.33333333]
 [0.125      0.         0.25      ]]
Addition : 
 [[2 1 3]
 [1 8 4]
 [9 1 5]]
Subtraction : 
 [[ 0 -1 -1]
 [-1 -6 -2]
 [-7 -1 -3]]
Dot : 
 [[9 2 6]
 [9 8 7]
 [9 2 6]]


In [25]:
print("Square : \n",np.square(arr))
print("Exponential : \n",np.exp(arr))
print("Log : \n",np.log10(brr))             # can't divide by zero

Square : 
 [[1 0 1]
 [0 1 1]
 [1 0 1]]
Exponential : 
 [[2.71828183 1.         2.71828183]
 [1.         2.71828183 2.71828183]
 [2.71828183 1.         2.71828183]]
Log : 
 [[0.         0.         0.30103   ]
 [0.         0.84509804 0.47712125]
 [0.90308999 0.         0.60205999]]
