# Numpy
<h4>Basic rand, rndn, randint ,seed, choice, permutation 

In [58]:
import numpy as np

In [14]:
arr = np.array([1,2,3])
tot = np.sum(arr)
print("Total ",tot)
print("Exp ",np.exp(arr))
print("Log ",np.log10(arr))

Total  6
Exp  [ 2.71828183  7.3890561  20.08553692]
Log  [0.         0.30103    0.47712125]


In [15]:
for x in arr:
    print(x)

1
2
3


In [31]:
brr = np.array([1,2,3]).T # Transpose of matrix
print("Normal ", brr)
for x in brr:
    print(x)

Normal  [1 2 3]
1
2
3


In [38]:
rndm = np.random.random((5,3)) # 5 row 3 column
print("Random 2d Array \n",rndm)

Random 2d Array 
 [[0.09036347 0.46406179 0.07782547]
 [0.26045416 0.5870357  0.76320394]
 [0.37956164 0.50816043 0.25840868]
 [0.96335992 0.1649744  0.64153585]
 [0.76419461 0.03887893 0.42488153]]


In [39]:
rndm = np.random.randint(1,5,(4,4)) # 1 - 5 range 4*4 matrix
print("Normal \n",rndm)
print("Transpose \n",rndm.T)

Normal 
 [[3 3 1 4]
 [1 4 3 3]
 [1 1 4 4]
 [1 3 1 4]]
Transpose 
 [[3 1 1 1]
 [3 4 1 3]
 [1 3 4 1]
 [4 3 4 4]]


In [42]:
rndm = np.random.randn(2,4,4) # 2 time 4*4 matrix -1 to 1
print(rndm)

[[[-0.85898545 -1.62184713 -1.38872867 -0.56343955]
  [-1.21208322 -0.47761041 -0.91276551 -0.25901626]
  [-0.73758179 -0.03620677  0.31678889 -0.42979328]
  [ 0.71269526 -0.37570592 -0.48986625  0.11297153]]

 [[-0.69442772  0.31033134  0.68839599  1.4336217 ]
  [-0.61347686  0.78291879 -1.26823287 -0.92582226]
  [-1.85966918  1.21187845 -1.30002597 -0.33892382]
  [ 0.01347796  0.13857357  0.78625346  2.1306687 ]]]


In [53]:
rndm = np.random.rand(2,4,4) # 2 time 4*4 matrix 0 to 1
print(rndm)

[[[0.39676747 0.53881673 0.41919451 0.6852195 ]
  [0.20445225 0.87811744 0.02738759 0.67046751]
  [0.4173048  0.55868983 0.14038694 0.19810149]
  [0.80074457 0.96826158 0.31342418 0.69232262]]

 [[0.87638915 0.89460666 0.08504421 0.03905478]
  [0.16983042 0.8781425  0.09834683 0.42110763]
  [0.95788953 0.53316528 0.69187711 0.31551563]
  [0.68650093 0.83462567 0.01828828 0.75014431]]]


In [43]:
rndm = np.random.randint(1,5,(2,4,4)) # 2, 4, 4 [2 time 4*4 matrix]
print(rndm)

[[[2 2 4 4]
  [3 4 3 3]
  [3 1 1 2]
  [1 1 2 3]]

 [[2 2 2 3]
  [3 4 3 4]
  [3 1 3 1]
  [2 3 3 4]]]


In [50]:
np.random.seed(1)                   # same value 
rndm = np.random.randint(1,5,(4,4))
print(rndm)

[[2 4 1 1]
 [4 2 4 2]
 [4 1 1 2]
 [1 4 2 1]]


In [52]:
np.random.seed(1)
rndm = np.random.randint(1,5,(4,4))
print(rndm)

[[2 4 1 1]
 [4 2 4 2]
 [4 1 1 2]
 [1 4 2 1]]


In [55]:
x = [1,2,3,4]                        # take random value from x
for i in range(20):
    print(np.random.choice(x),end=" ")

1 3 2 4 4 3 4 2 1 4 2 2 4 3 1 1 3 3 4 4 

In [56]:
for i in range(5):                   # random permutation
    print(np.random.permutation(x))

[1 3 2 4]
[2 3 1 4]
[2 1 4 3]
[4 3 2 1]
[4 3 1 2]
